name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
     - cron:  '0 4 * * *' # daily at 4am
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v3
    - name: Fetch latest data
      run: |-
        sudo apt-get install gdal-bin
        npm i
        npm i --global topojson-server zx
        zx index.mjs 
        ls -ali
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git config http.postBuffer 524288000
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git pull --rebase
        git push


